//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototypeDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrototypeEntities : DbContext
    {
        public PrototypeEntities()
            : base("name=PrototypeEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<film> films { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<planet> planets { get; set; }
        public DbSet<species> species { get; set; }
        public DbSet<starship> starships { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<transport> transports { get; set; }
        public DbSet<vehicle> vehicles { get; set; }

    }
}
