//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototypeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public int id { get; set; }
        public string cargo_capacity { get; set; }
        public string consumables { get; set; }
        public string cost_in_credits { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string crew { get; set; }
        public Nullable<System.DateTime> edited { get; set; }
        public string length { get; set; }
        public string manufacturer { get; set; }
        public string max_atmosphering_speed { get; set; }
        public string model { get; set; }
        public string name { get; set; }
        public string passengers { get; set; }
    }
}
